/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0064e0',
        'primary-deep': '#0457cb',
        'primary-soft': '#0091ff',
        'on-primary': '#ffffff',
        'ink-button': '#000000',
        'on-ink-button': '#ffffff',
        'fb-blue': '#1876f2',
        'meta-link': '#385898',
        'oculus-purple': '#a121ce',
        success: '#31a24c',
        'success-bg': '#24e400',
        attention: '#f2a918',
        warning: '#f7b928',
        'warning-bg': '#ffe200',
        critical: '#e41e3f',
        'critical-strong': '#f0284a',
        canvas: '#ffffff',
        'surface-soft': '#f1f4f7',
        'ink-deep': '#0a1317',
        ink: '#1c1e21',
        charcoal: '#444950',
        slate: '#4b4c4f',
        steel: '#5d6c7b',
        stone: '#8595a4',
        hairline: '#ced0d4',
        'hairline-soft': '#dee3e9',
        'disabled-text': '#bcc0c4',
      },
      borderRadius: {
        'xs': '2px',
        'sm': '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '16px',
        'xxl': '24px',
        'xxxl': '32px',
        'feature': '40px',
        'full': '100px',
      },
      spacing: {
        'margin-mobile': '16px',
        'container-max': '1440px',
        'stack-md': '16px',
        'gutter': '24px',
        'stack-sm': '8px',
        'stack-lg': '24px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        sans: ['Montserrat', 'Geist', 'Inter', 'sans-serif'],
        mono: ['Geist Mono', 'JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
